import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/skeleton/footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html style={{height: "100%"}} lang="en">
      <body style={{height: "100%", scrollPadding: 0, scrollBehavior: 'unset'}} className={inter.className}>
        
        {children}
      
      <Footer />
      </body>
    </html>
  )
}
